In [113]:
# pip install seaborn

In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import precision_score, recall_score, f1_score


In [115]:
def load_data():
    heart=pd.read_csv('heart.csv')
    lung=pd.read_csv('lung.csv')
    db=pd.read_csv('diabetes.csv')
    kidney=pd.read_csv('kidney.csv')
    return heart,lung,db,kidney

In [116]:
heart,lung,db,kidney = load_data()

In [117]:
kidney

id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no   
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [118]:
lung.columns = lung.columns.str.lower().str.replace(' ','_')
heart.columns = heart.columns.str.lower().str.replace(' ','_')
kidney.columns = kidney.columns.str.lower().str.replace(' ','_')
db.columns = db.columns.str.lower().str.replace(' ','_')

In [119]:
# COLUMNS TO KEEP

heart = heart[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh', 'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output']]
lung = lung[['age', 'smoking', 'yellow_fingers', 'anxiety', 'peer_pressure', 'chronic_disease', 'fatigue_', 'allergy_', 'wheezing', 'alcohol_consuming', 'coughing', 'shortness_of_breath', 'swallowing_difficulty', 'chest_pain', 'lung_cancer']]
db = db[['pregnancies','glucose','bloodpressure','skinthickness','insulin','bmi','diabetespedigreefunction','age','outcome']]

In [120]:
def show_data():
    print('HEART',heart.head())
    print('LUNG',lung.head())
    # print('KIDNEY',kidney.head())
    print('DIABETES',db.head())
show_data()

HEART    age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1  
LUNG    age  smoking  yellow_fingers  anxiety  peer_pressure  chronic_disease  \
0   69        1               2        2              1                1   
1   74        2               1        1              1                2   
2   59        1               1        1              2                1   
3   63        2               2        2              1                1   
4 

In [121]:
kidney = kidney.dropna()
kidney

id   age    bp     sg   al   su       rbc        pc         pcc  \
3      3  48.0  70.0  1.005  4.0  0.0    normal  abnormal     present   
9      9  53.0  90.0  1.020  2.0  0.0  abnormal  abnormal     present   
11    11  63.0  70.0  1.010  3.0  0.0  abnormal  abnormal     present   
14    14  68.0  80.0  1.010  3.0  2.0    normal  abnormal     present   
20    20  61.0  80.0  1.015  2.0  0.0  abnormal  abnormal  notpresent   
..   ...   ...   ...    ...  ...  ...       ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0    normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0    normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0    normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0    normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0    normal    normal  notpresent   

             ba  ...  pcv     wc   rc  htn   dm  cad appet   pe  ane  \
3    notpresent  ...   32   6700  3.9  yes   no   no  poor  yes  yes   
9    notpresent  ...   29  12100  3.7  yes  yes   no  poor   no  yes   
11   notpresent  ...   32   4500  3.8  yes  yes   no  poor  yes   no   
14      present  ...   16  11000  2.6  yes  yes  yes  poor  yes   no   
20   notpresent  ...   24   9200  3.2  yes  yes  yes  poor  yes  yes   
..          ...  ...  ...    ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47   6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54   7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49   6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51   7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53   6800  6.1   no   no   no  good   no   no   

    classification  
3              ckd  
9              ckd  
11             ckd  
14             ckd  
20             ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[158 rows x 26 columns]

In [122]:
# lungvalues = lung.values
# # kidneyvalues = kidney.values
# heartvalues = heart.values
# dbvalues = db.values

# # Initialize label encoders
# lbllung = LabelEncoder()
# # lblkidney = LabelEncoder()
# lblheart = LabelEncoder()
# lbldb = LabelEncoder()

# # Fit and transform the data
# lung_encoded = lbllung.fit_transform(lungvalues)
# kidney_encoded = lblkidney.fit_transform(kidneyvalues)
# heart_encoded = lblheart.fit_transform(heartvalues)
# db_encoded = lbldb.fit_transform(dbvalues)

In [123]:
columns_to_transform_for_lung = ['smoking','yellow_fingers','anxiety','peer_pressure','chronic_disease','fatigue_','allergy_','wheezing','alcohol_consuming','coughing','shortness_of_breath','swallowing_difficulty','chest_pain','lung_cancer']
lung[columns_to_transform_for_lung] = lung[columns_to_transform_for_lung].replace({1:0,2:1,'YES':1,'NO':0})
lung

C:\Users\Admin\AppData\Local\Temp\ipykernel_15200\1889828643.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lung[columns_to_transform_for_lung] = lung[columns_to_transform_for_lung].replace({1:0,2:1,'YES':1,'NO':0})


age  smoking  yellow_fingers  anxiety  peer_pressure  chronic_disease  \
0     69        0               1        1              0                0   
1     74        1               0        0              0                1   
2     59        0               0        0              1                0   
3     63        1               1        1              0                0   
4     63        0               1        0              0                0   
..   ...      ...             ...      ...            ...              ...   
304   56        0               0        0              1                1   
305   70        1               0        0              0                0   
306   58        1               0        0              0                0   
307   67        1               0        1              0                0   
308   62        0               0        0              1                0   

     fatigue_  allergy_  wheezing  alcohol_consuming  coughing  \
0           1         0         1                  1         1   
1           1         1         0                  0         0   
2           1         0         1                  0         1   
3           0         0         0                  1         0   
4           0         0         1                  0         1   
..        ...       ...       ...                ...       ...   
304         1         0         0                  1         1   
305         1         1         1                  1         1   
306         0         1         1                  1         1   
307         1         1         0                  1         1   
308         1         1         1                  1         0   

     shortness_of_breath  swallowing_difficulty  chest_pain  lung_cancer  
0                      1                      1           1            1  
1                      1                      1           1            1  
2                      1                      0           1            0  
3                      0                      1           1            0  
4                      1                      0           0            0  
..                   ...                    ...         ...          ...  
304                    1                      1           0            1  
305                    1                      0           1            1  
306                    0                      0           1            1  
307                    1                      0           1            1  
308                    0                      1           0            1  

[309 rows x 15 columns]

In [124]:
xlung = lung.iloc[:,:-1]
ylung = lung.iloc[:,-1]
xheart = heart.iloc[:,:-1]
yheart = heart.iloc[:,-1]
xdb = db.iloc[:,:-1]
ydb = db.iloc[:,-1]

In [125]:
# HEART SCALING
heart_scaler = MinMaxScaler()
heart_scaled = heart_scaler.fit_transform(xheart)

# Convert the scaled array back to a DataFrame and preserve column names
xheart = pd.DataFrame(heart_scaled, columns=xheart.columns)

# Check the result
print(heart.head())


   age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1  


In [126]:
#LUNG SCALING
lung_scaler = MinMaxScaler()
lung_scaled = lung_scaler.fit_transform(xlung)
xlung = pd.DataFrame(lung_scaled,columns=xlung.columns)
# print(lung.head())

In [127]:
#DIABETEST SCALING
db_scaler = MinMaxScaler()
db_scaled = db_scaler.fit_transform(xdb)
xdb=pd.DataFrame(db_scaled,columns=xdb.columns)
# print(db.head())

In [128]:
xtrainheart,xtestheart,ytrainheart,ytestheart = train_test_split(xheart,yheart,test_size=0.2,random_state=0)
xtrainlung,xtestlung,ytrainlung,ytestlung = train_test_split(xlung,ylung,test_size=0.2,random_state=0)
xtraindb,xtestdb,ytraindb,ytestdb = train_test_split(xdb,ydb,test_size=0.2,random_state=0)

In [129]:
#LUNG ALGORITHM SELECTION 
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100,random_state=42),
    "SVM": SVC(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(max_iter=1000, random_state=42)
}

# Train, predict and evaluate each model
for name, model in models.items():
    model.fit(xtrainlung, ytrainlung)
    predictions = model.predict(xtestlung)
    accuracy = accuracy_score(ytestlung, predictions)
    print(f'{name} Accuracy: {accuracy}')
    # Precision, Recall, F1-Score
    precision = precision_score(ytestlung, predictions)
    recall = recall_score(ytestlung, predictions)
    f1 = f1_score(ytestlung, predictions)

    print(f'Precision: {precision}')
    print(f'Recall: {recall}')
    print(f'F1-Score: {f1}')
    print("Confusion Matrix:")
    print(confusion_matrix(ytestlung, predictions))
    print('-------------------------')

Logistic Regression Accuracy: 0.9193548387096774


Precision: 0.9272727272727272
Recall: 0.9807692307692307
F1-Score: 0.9532710280373832
Confusion Matrix:
[[ 6  4]
 [ 1 51]]
-------------------------
Random Forest Accuracy: 0.8870967741935484
Precision: 0.8947368421052632
Recall: 0.9807692307692307
F1-Score: 0.9357798165137615
Confusion Matrix:
[[ 4  6]
 [ 1 51]]
-------------------------
SVM Accuracy: 0.9032258064516129
Precision: 0.9107142857142857
Recall: 0.9807692307692307
F1-Score: 0.9444444444444444
Confusion Matrix:
[[ 5  5]
 [ 1 51]]
-------------------------
KNN Accuracy: 0.8387096774193549
Precision: 0.8620689655172413
Recall: 0.9615384615384616
F1-Score: 0.9090909090909091
Confusion Matrix:
[[ 2  8]
 [ 2 50]]
-------------------------
Gradient Boosting Accuracy: 0.8709677419354839
Precision: 0.8793103448275862
Recall: 0.9807692307692307
F1-Score: 0.9272727272727272
Confusion Matrix:
[[ 3  7]
 [ 1 51]]
-------------------------
Naive Bayes Accuracy: 0.8709677419354839
Precision: 0.9074074074074074
Recall: 0.9423076923076923
F

In [130]:
#HEART ALGORITHM SELECTION
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=1000,random_state=42),
    "SVM": SVC(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(max_iter=1000, random_state=42)
}

# Train, predict and evaluate each model
for name, model in models.items():
    model.fit(xtrainheart, ytrainheart)
    predictions = model.predict(xtestheart)
    accuracy = accuracy_score(ytestheart, predictions)
    print(f'{name} Accuracy: {accuracy}')
    precision = precision_score(ytestheart, predictions)
    recall = recall_score(ytestheart, predictions)
    f1 = f1_score(ytestheart, predictions)

    print(f'Precision: {precision}')
    print(f'Recall: {recall}')
    print(f'F1-Score: {f1}')
    print("Confusion Matrix:")
    print(confusion_matrix(ytestheart, predictions))
    print('-------------------------')

Logistic Regression Accuracy: 0.8360655737704918
Precision: 0.8157894736842105
Recall: 0.9117647058823529
F1-Score: 0.8611111111111112
Confusion Matrix:
[[20  7]
 [ 3 31]]
-------------------------
Random Forest Accuracy: 0.8524590163934426
Precision: 0.8571428571428571
Recall: 0.8823529411764706
F1-Score: 0.8695652173913043
Confusion Matrix:
[[22  5]
 [ 4 30]]
-------------------------
SVM Accuracy: 0.8360655737704918
Precision: 0.8
Recall: 0.9411764705882353
F1-Score: 0.8648648648648649
Confusion Matrix:
[[19  8]
 [ 2 32]]
-------------------------
KNN Accuracy: 0.8688524590163934
Precision: 0.8611111111111112
Recall: 0.9117647058823529
F1-Score: 0.8857142857142857
Confusion Matrix:
[[22  5]
 [ 3 31]]
-------------------------
Gradient Boosting Accuracy: 0.819672131147541
Precision: 0.8285714285714286
Recall: 0.8529411764705882
F1-Score: 0.8405797101449275
Confusion Matrix:
[[21  6]
 [ 5 29]]
-------------------------
Naive Bayes Accuracy: 0.8524590163934426
Precision: 0.837837837837

c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [131]:
#DIABETES ALGORITHM SELECTION
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=1000,random_state=42),
    "SVM": SVC(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(max_iter=1000, random_state=42)
}

# Train, predict and evaluate each model
for name, model in models.items():
    model.fit(xtraindb, ytraindb)
    predictions = model.predict(xtestdb)
    accuracy = accuracy_score(ytestdb, predictions)
    print(f'{name} Accuracy: {accuracy}')
    precision = precision_score(ytestdb, predictions)
    recall = recall_score(ytestdb, predictions)
    f1 = f1_score(ytestdb, predictions)

    print(f'Precision: {precision}')
    print(f'Recall: {recall}')
    print(f'F1-Score: {f1}')
    print("Confusion Matrix:")
    print(confusion_matrix(ytestdb, predictions))
    print('-------------------------')

Logistic Regression Accuracy: 0.8181818181818182
Precision: 0.7714285714285715
Recall: 0.574468085106383
F1-Score: 0.6585365853658537
Confusion Matrix:
[[99  8]
 [20 27]]
-------------------------
Random Forest Accuracy: 0.8181818181818182
Precision: 0.7111111111111111
Recall: 0.6808510638297872
F1-Score: 0.6956521739130435
Confusion Matrix:
[[94 13]
 [15 32]]
-------------------------
SVM Accuracy: 0.7987012987012987
Precision: 0.7222222222222222
Recall: 0.5531914893617021
F1-Score: 0.6265060240963856
Confusion Matrix:
[[97 10]
 [21 26]]
-------------------------
KNN Accuracy: 0.7792207792207793
Precision: 0.6585365853658537
Recall: 0.574468085106383
F1-Score: 0.6136363636363636
Confusion Matrix:
[[93 14]
 [20 27]]
-------------------------
Gradient Boosting Accuracy: 0.8116883116883117
Precision: 0.6875
Recall: 0.7021276595744681
F1-Score: 0.6947368421052632
Confusion Matrix:
[[92 15]
 [14 33]]
-------------------------
Naive Bayes Accuracy: 0.7922077922077922
Precision: 0.6744186046

In [132]:
# lung->logistic
# heart->neural
# diabetes->randomforest

lungmodel = LogisticRegression(max_iter=1000, random_state=42)
lungmodel.fit(xtrainlung,ytrainlung)
heartmodel =  MLPClassifier(max_iter=1000, random_state=42)
heartmodel.fit(xtrainheart,ytrainheart)
dbmodel = RandomForestClassifier(n_estimators=1000,random_state=42)
dbmodel.fit(xtraindb,ytraindb)

c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


RandomForestClassifier(n_estimators=1000, random_state=42)

In [133]:
import joblib

# Save the trained models
joblib.dump(lungmodel, 'logistic_regression_lung_model.pkl')
joblib.dump(heartmodel, 'neural_network_heart_model.pkl')
joblib.dump(dbmodel, 'random_forest_diabetes_model.pkl')

['random_forest_diabetes_model.pkl']

In [134]:
# joblib.dump(xheart, 'heart_scaler_input.pkl')
# joblib.dump(yheart, 'heart_scaler_output.pkl')
# joblib.dump(xlung, 'lung_scaler_input.pkl')
# joblib.dump(ylung, 'lung_scaler_output.pkl')
# joblib.dump(xdb, 'db_scaler_input.pkl')
# joblib.dump(ydb, 'db_scaler_output.pkl')
joblib.dump(heart_scaler, 'heart_scaler.pkl')
joblib.dump(lung_scaler, 'lung_scaler.pkl')
joblib.dump(db_scaler, 'db_scaler.pkl')

['db_scaler.pkl']